services:

  django_web:
    build:
      context: .
      dockerfile: Dockerfile

    deploy:

      resources:
        limits:
          cpus: "1.8"
          memory: "950m"  # Limits to 1 GB of RAM

    entrypoint: ["/app/entrypoint.prod.sh"] # Fixed indentation
  
    environment:

      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    
    network_mode: "host"


  frontend_proxy:
    build:
      context: .
      dockerfile: nginx.Dockerfile  
   
    ports:
      - 443:443
  
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
       - ./project/certs/nginx.crt:/etc/nginx/ssl/nginx.crt:ro
       - ./project/certs/nginx.key:/etc/nginx/ssl/nginx.key:ro
       - ./project/statics:/usr/share/nginx/html/static:ro
    
    depends_on:
      - django_web
        
    network_mode: "host"





    
  






