# Generated by Django 5.2 on 2025-04-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countdata",
            name="date",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="countdata",
            name="datetime",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="countdata",
            name="linecount1",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="countdata",
            name="linecount2",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="countdata",
            name="polygon1count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="countdata",
            name="polygon2count",
            field=models.IntegerField(default=0),
        ),
    ]
