# Generated by Django 5.2 on 2025-04-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0002_alter_countdata_date_alter_countdata_datetime_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="countdata",
            name="APP_countda_timeste_c6bde6_idx",
        ),
        migrations.RemoveField(
            model_name="countdata",
            name="timestep",
        ),
        migrations.AlterField(
            model_name="countdata",
            name="date",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AlterField(
            model_name="countdata",
            name="datetime",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
    ]
