# Generated by Django 5.2 on 2025-04-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0003_remove_countdata_app_countda_timeste_c6bde6_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountData_for_Line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(blank=True, default="", max_length=8)),
                ("linecount1", models.IntegerField(default=0)),
                ("linecount2", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="CountData_for_polygon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.CharField(blank=True, default="", max_length=8)),
                ("polygon1count", models.IntegerField(default=0)),
                ("polygon2count", models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="CountData",
        ),
    ]
