# Generated by Django 5.2 on 2025-04-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CountData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestep", models.DateTimeField(auto_now_add=True)),
                ("date", models.CharField(max_length=8)),
                ("datetime", models.CharField(max_length=8)),
                ("linecount1", models.IntegerField()),
                ("linecount2", models.IntegerField()),
                ("polygon1count", models.IntegerField()),
                ("polygon2count", models.IntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["timestep"], name="APP_countda_timeste_c6bde6_idx"
                    )
                ],
            },
        ),
    ]
