name: Django CI
on:
  push:
    branches: [ "another_plan" ]
  pull_request:
    branches: [ "another_plan" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}




      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Docker Buildx (optional, remove if not needed for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ruizhong123/project_version5-web:upload

      # build and push Nginx Docker image
      - name: build and push Nginx Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ruizhong123/project_version5-nginx:upload
      
    # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Create a Docker Compose file
      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
          for i in {1..10}; do
            curl -k -f https://localhost:443 && break || sleep 5
          done
          docker-compose -f docker-compose.yml logs
  







